apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-artifact-extractor
  namespace: cloud-artifact-extractor
  labels:
    app: cloud-artifact-extractor
  # For AWS EKS OIDC:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cloud-artifact-extractor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-artifact-extractor
  namespace: cloud-artifact-extractor
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['pods', 'pods/log']
    verbs: ['get', 'list']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-artifact-extractor
  namespace: cloud-artifact-extractor
subjects:
  - kind: ServiceAccount
    name: cloud-artifact-extractor
    namespace: cloud-artifact-extractor
roleRef:
  kind: Role
  name: cloud-artifact-extractor
  apiGroup: rbac.authorization.k8s.io
