# Jekyll Configuration for GitHub Pages
title: "Cloud Artifact Extractor"
description: "A FastAPI-based service for extracting and managing cloud service artifacts from AWS, Azure, and GCP"
url: "https://ramesh-pegasys.github.io"
baseurl: "/csp-scanner"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-seo-tag

# Navigation
navigation:
  - title: "Home"
    url: "/csp-scanner/index.html"
  - title: "Getting Started"
    url: "/csp-scanner/getting-started.html"
  - title: "Configuration"
    url: "/csp-scanner/configuration.html"
  - title: "Cloud Providers"
    url: "/csp-scanner/cloud-providers.html"
  - title: "Supported Resources"
    url: "/csp-scanner/supported-resources.html"
  - title: "Metadata Structure"
    url: "/csp-scanner/metadata-structure.html"
  - title: "Implementation Details"
    url: "/csp-scanner/implementation-details.html"
  - title: "API Reference"
    url: "/csp-scanner/api-reference.html"
  - title: "Troubleshooting"
    url: "/csp-scanner/troubleshooting.html"
  - title: "Development"
    url: "/csp-scanner/development.html"

# Exclude from processing
exclude:
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .vscode/
  - .github/

# Include files
include:
  - _pages

# SEO and social
author: "Pegasys.ai"
social:
  name: Cloud Artifact Extractor
  links:
    - https://www.pegasys.ai

# Custom variables
logo: /assets/images/logo.png
github_username: ramesh-pegasys
repo: csp-scanner

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: "Cloud Security Team"